In [7]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])

In [25]:
type(a)

numpy.ndarray

In [26]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [16]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.full((3,5),3,dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [19]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [22]:
np.random.normal(10,4,(3,4))

array([[13.89737732,  9.1295223 , 13.34037272,  7.82288172],
       [ 7.5336137 , 12.41949362, 11.78372504,  1.71193654],
       [ 8.04597919, 10.82114617, 10.3632201 , 10.69983304]])

In [30]:
np.random.randint(0,10,(3,3)) #0'dan 10 a kadar random int üretir

array([[3, 9, 8],
       [2, 3, 2],
       [8, 9, 9]])

In [32]:
np.random.randint(10,size=10)#0'dan 10a kadar 10 elemanlı random array

array([1, 4, 7, 2, 7, 3, 3, 0, 5, 4])

In [33]:
a = np.random.randint(10,size=10)

In [34]:
a.ndim # boyutun kac boyutlu oldugu

1

In [36]:
a.shape #array boyutunu tam olarak verir

(10,)

In [37]:
a.size #eleman sayisi

10

In [38]:
a.dtype #icerideki verinin turunu veriri.

dtype('int32')

In [39]:
b = np.random.randint(10,size=(3,5)) #3'e 5 lik bir matris random

In [40]:
b

array([[8, 6, 4, 5, 0],
       [2, 1, 5, 7, 8],
       [5, 2, 3, 0, 2]])

In [41]:
b.ndim

2

In [42]:
b.shape

(3, 5)

In [43]:
b.size

15

In [44]:
b.dtype

dtype('int32')

In [46]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(1,10).reshape((3,3)) #boyut değiştirme reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a = np.arange(1,10)

In [49]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
#--------------Array Birlestirme-----------------

In [52]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [53]:
np.concatenate([x,y]) # birlestirme fonksiyonu

array([1, 2, 3, 4, 5, 6])

In [54]:
z = np.array([7,8,9])

In [55]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a = np.array([[1,2,3],[4,5,6]])


In [63]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [64]:
np.concatenate([a,a],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [65]:
#----------------Array Ayirma Islemleri------------------

In [66]:
x = np.array([1,2,3,99,99,3,2,1])

In [67]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [68]:
a,b,c = np.split(x,[3,5])

In [69]:
a

array([1, 2, 3])

In [70]:
b

array([99, 99])

In [71]:
c

array([3, 2, 1])

In [72]:
#iki boyutlu ayirma

In [73]:
m = np.arange(16).reshape(4,4)

In [74]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [76]:
v = np.array([3,47,98,12,2,1,77])
v

array([ 3, 47, 98, 12,  2,  1, 77])

In [80]:
np.sort(v) # array sıralama

array([ 1,  2,  3, 12, 47, 77, 98])

In [87]:
m = np.random.normal(20,5,(3,3))
m

array([[12.14900203, 21.0267467 , 30.05898952],
       [24.57746183, 16.59124199, 21.1146363 ],
       [18.44844774, 11.21138663, 28.8539378 ]])

In [85]:
np.sort(m,axis=1)

array([[15.90536563, 22.34420638, 34.11125868],
       [24.47677305, 25.10897662, 25.20382256],
       [17.54574602, 19.4257444 , 23.15094389]])

In [86]:
np.sort(m,axis = 0)

array([[19.4257444 , 17.54574602, 15.90536563],
       [25.10897662, 22.34420638, 23.15094389],
       [34.11125868, 25.20382256, 24.47677305]])